### ISSUE TITLE
Questions about main.py  'multiprocessing'

### ISSUE THREAD

**Issue by Beat-in-our-hearts** [YunxuanMao/ngel_slam#9]
I follow the Sec. Run, cmd is 
````
python main.py --config configs/Replica/room0.yaml  --input_folder /home/nice-slam/Datasets/Replica/room0 --output outputs/
````
````
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 41, in main
    pipeline.run()
  File "/home/catkin_ws/src/ngel_slam/src/ngel_slam.py", line 202, in run
    p.start()
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/root/miniforge3/envs/ngel/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object
````

**Comment by YunxuanMao** [comment]
There are some conflicts between ROS and python multiprocess. Please try the json version.

**Comment by Beat-in-our-hearts** [comment]
> There are some conflicts between ROS and python multiprocess. Please try the json version.

Can you give a more detailed solution?

**Comment by Beat-in-our-hearts** [comment]
> > There are some conflicts between ROS and python multiprocess. Please try the json version.
> 
> Can you give a more detailed solution?

I tried to run the following code, but the process did not give any feedback (did not stop) after the output of the following information, I used the docker image with opengl, cuda, ros

````
python main_json.py --config configs/Replica/room0.yaml  --input_folder /home/nice-slam/Datasets/Replica/room0 --output outputs/
````

````
Output folder: output/Replica/room0_ORB_cl/7_2_20000_10
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth

````

**Comment by YunxuanMao** [comment]
> > > There are some conflicts between ROS and python multiprocess. Please try the json version.
> > 
> > 
> > Can you give a more detailed solution?
> 
> I tried to run the following code, but the process did not give any feedback (did not stop) after the output of the following information, I used the docker image with opengl, cuda, ros
> 
> ```
> python main_json.py --config configs/Replica/room0.yaml  --input_folder /home/nice-slam/Datasets/Replica/room0 --output outputs/
> ```
> 
> ```
> Output folder: output/Replica/room0_ORB_cl/7_2_20000_10
> Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
> /root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
>   warnings.warn(
> /root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
>   warnings.warn(msg)
> Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
> Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
> Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
> ```
Have you generated the json documents by orb-slam3?

**Comment by Mekjeri** [comment]
Hello, I would like to ask about a version conflict with scipy during dependency installation. Would it be feasible to install scipy version 1.7.2 and downgrade scikit-image to version 0.19.3 to resolve this issue?
![2024-09-20 16-01-44屏幕截图](https://github.com/user-attachments/assets/a83fd852-975b-4784-a680-e1bb5c707b39)

**Comment by Beat-in-our-hearts** [comment]
> Have you generated the json documents by orb-slam3?

I installed your method to generate yaml files, it works, but found various other bugs in running, which was very disappointing, I may create a new issue later to show the bugs I have encountered so far.

**Comment by Beat-in-our-hearts** [comment]
> Hello, I would like to ask about a version conflict with scipy during dependency installation. Would it be feasible to install scipy version 1.7.2 and downgrade scikit-image to version 0.19.3 to resolve this issue?

I tried:
````
pip uninstall scikit-image
pip install scikit-image==0.17.1
````
and fixed:`import skimage` to `from skimage import measure`

**Comment by Mekjeri** [comment]
> > 您好，我想询问一下在依赖项安装过程中与 scipy 的版本冲突。安装 scipy 版本 1.7.2 并将 scikit-image 降级到版本 0.19.3 以解决此问题是否可行？
> 
> 我试过了：
> 
> ```
> pip uninstall scikit-image
> pip install scikit-image==0.17.1
> ```
> 
> 并固定：更改为`import skimage``from skimage import measure`

ok, thanks!

**Comment by Mekjeri** [comment]
> > Hello, I would like to ask about a version conflict with scipy during dependency installation. Would it be feasible to install scipy version 1.7.2 and downgrade scikit-image to version 0.19.3 to resolve this issue?
> 
> I tried:
> 
> ```
> pip uninstall scikit-image
> pip install scikit-image==0.17.1
> ```
> 
> and fixed:`import skimage` to `from skimage import measure`

ok, thanks!

**Comment by zxhqy** [comment]
> > 您是否已通过orb-slam3生成json文档？
> 
> 我安装了您的方法来生成 yaml 文件，它可以工作，但在运行中发现了各种其他错误，这非常令人失望，我可能会稍后创建一个新的问题来展示我迄今为止遇到的错误。

请问您如何生成的yaml文件

**Comment by zxhqy** [comment]
> > > There are some conflicts between ROS and python multiprocess. Please try the json version.
> > 
> > 
> > Can you give a more detailed solution?
> 
> I tried to run the following code, but the process did not give any feedback (did not stop) after the output of the following information, I used the docker image with opengl, cuda, ros
> 
> ```
> python main_json.py --config configs/Replica/room0.yaml  --input_folder /home/nice-slam/Datasets/Replica/room0 --output outputs/
> ```
> 
> ```
> Output folder: output/Replica/room0_ORB_cl/7_2_20000_10
> Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
> /root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
>   warnings.warn(
> /root/miniforge3/envs/ngel/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
>   warnings.warn(msg)
> Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
> Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
> Loading model from: /root/miniforge3/envs/ngel/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
> ```

I ran orb_slam3_ros and generated JSON files, and saved them in the same directory as the dataset. Then, when I ran main_json.py, the same problem as yours occurred. Could you please share how to solve it?
